### PR TITLE
🏷️   Add typings for validate() method.

### PR DESCRIPTION
**Pull request by rsfarias**
Adds type definitions for the validate method of Pagar.me API, used for checking if card input is valid and to return the brand of the card (Visa, Mastercard etc.).

References: 
- https://pagarme.github.io/pagarme-js/module-validations.html
- https://pagarme.github.io/pagarme-js/validations_index.js.html#line69

### CODE REVIEW

**Comment by jonyw4** [comment]
Just the next time that you commit, please commit with the [Angular Commit Message Conventions](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines). This repo uses [Semantic Release](https://github.com/semantic-release/semantic-release) to publish and maintain versions. So if you don't use the commit with the right conventions it will not publish in NPM. 😁

**Comment by jonyw4** [comment]
@all-contributors please add @rsfarias! for code

**Comment by jonyw4** [comment]
@all-contributors please add @rsfarias for code

**Comment by rsfarias** [comment]
> Just the next time that you commit, please commit with the [Angular Commit Message Conventions](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines). This repo uses [Semantic Release](https://github.com/semantic-release/semantic-release) to publish and maintain versions. So if you don't use the commit with the right conventions it will not publish in NPM. 😁

Cool, I'll make sure to follow that. Thanks for organizing this repo, @jonyw4!

**Pull request merged**
